version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/book"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
